DROP  TABLE if EXISTS OIRAPSurveys;
DROP  TABLE if EXISTS OIRAPSpeakers;
DROP  TABLE if EXISTS OIRAPExperts;

CREATE TABLE OIRAPSurveys (
	I_ID CHAR(16) NOT NULL,
	EMPLOYEE_ID BIGINT(20) NOT NULL,
	FIRST_NM 	VARCHAR(255),
	MIDDLE_NM 	VARCHAR(255),
	LAST_NM	 	VARCHAR(255),
  	TITLE_DESCR VARCHAR(255),
	EMAIL_ADDR 	VARCHAR(255),
	HOMEPAGE_URL VARCHAR(255),
	PHOTO_URL	VARCHAR(255),
	CAMPUS_CODE VARCHAR(255),
	CAMPUS_DESCR VARCHAR(255),
	DIVISION_CODE  VARCHAR(20),
	DIVISION_DESCR VARCHAR(255),
	DEPT_CODE 	VARCHAR(20),
	DEPT_DESCR  VARCHAR(255),
	REPORTING_REL_CODE 	VARCHAR(20),
	REPORTING_REL_DESCR VARCHAR(255),
  	ADDR_1 	VARCHAR(255) NOT NULL,
 	ADDR_2 	VARCHAR(255) NOT NULL,
	CITY  	VARCHAR(255),
	STATE  	VARCHAR(5),
	ZIP  	VARCHAR(10),
	PHONE  	VARCHAR(20),
	PHONE_EXT  	VARCHAR(20),
	FAX  		VARCHAR(20),
	COS_IND TINYINT(1) DEFAULT '0',
	COS_TRANS_DT VARCHAR(30),
	IS_PROFILE_PRIVATE_FLAG TINYINT(1) DEFAULT '0',
	IS_RESUME_PRIVATE_FLAG 	TINYINT(1) DEFAULT '0',
	IS_ADMIN_FLAG 			TINYINT(1) DEFAULT '0',
	IS_USING_FACSURV 		TINYINT(1) DEFAULT '0',
	PHONE2 		VARCHAR(20),
	PHONE2_EXT 	VARCHAR(15),
	JOB_BEGIN_DATE VARCHAR(20),
	JOB_CLASS 	VARCHAR(15),
	SOURCE_FLAG  	TINYINT(1),
	UPDATE_NAME 	TINYINT(1),
	EMPLOYMENT_STATUS_CODE VARCHAR(5),
	TENURE_DATE 	VARCHAR(20),
	RANK_CODE 		CHAR(10),
	EMPLOYEE_TYPE_CODE CHAR(8),
	PPROFILE 		CHAR(10),
	
  	ISINACTIVE TINYINT(1) DEFAULT '0',
  	SURVEYDATA TEXT,
  	LASTMODIFIED datetime, 
  	DATECREATED  datetime,  
  	PRIMARY KEY (I_ID)
);

CREATE TABLE OIRAPSpeakers (
	I_ID CHAR(16) NOT NULL,
	ALT_OFFICE_PHONE char(20),
	ALT_OFFICE_PHONE_EXT char(15),
	HOME_PHONE CHAR(20),
	PREFERRED_CONTACT CHAR(255),
	BIO TEXT,
	KEY_TOPICS TEXT,
	RESTRICTIONS TEXT,
	PRIMARY KEY (I_ID)
);

CREATE TABLE IF NOT EXISTS OIRAPExperts (
	I_ID CHAR(16) NOT NULL,
	ALT_OFFICE_PHONE CHAR(20),
	ALT_OFFICE_PHONE_EXIT CHAR(15),
	HOME_PHONE CHAR(20),
	HPHONE_DISPLAY_IND TINYINT(1) default 0,
	CELL_PHONE CHAR(20),
	CPHONE_DISPLAY_IND CHAR(20),
	ALT_EMAIL CHAR(255),
	PREFERRED_CONTACT CHAR(255),
	MEDIA_REDIRECT_CONTACT_IND TINYINT(1) DEFAULT 0,
	BIO TEXT,
	KEY_TOPICS TEXT,
	PRIMARY KEY (I_ID)
);